# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='APP \u540d\u79f0', max_length=255, verbose_name='name')),
                ('title', models.CharField(blank=True, help_text='APP \u6807\u9898', max_length=255, null=True, verbose_name='title')),
                ('image', models.ImageField(blank=True, help_text='APP \u56fe\u6807', null=True, upload_to=b'app', verbose_name='image')),
                ('descr', models.TextField(blank=True, help_text='APP \u63cf\u8ff0', null=True, verbose_name='description')),
                ('position', models.IntegerField(blank=True, default=0, help_text='APP \u4f4d\u7f6e', null=True, verbose_name='position')),
                ('display', models.BooleanField(default=True, help_text='APP \u662f\u5426\u663e\u793a True for display && False for not display', verbose_name='display')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='\u6dfb\u52a0\u65f6\u95f4', verbose_name='createtime')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='\u4fee\u6539\u65f6\u95f4', verbose_name='modifytime')),
            ],
            options={
                'db_table': 'appinfo',
                'verbose_name': 'appinfo',
                'verbose_name_plural': 'appinfo',
            },
        ),
        migrations.CreateModel(
            name='FunctionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='APP \u529f\u80fd\u540d\u79f0', max_length=255, verbose_name='name')),
                ('title', models.CharField(blank=True, help_text='APP \u529f\u80fd\u6807\u9898', max_length=255, null=True, verbose_name='title')),
                ('image', models.ImageField(blank=True, help_text='APP \u529f\u80fd\u56fe\u6807', null=True, upload_to=b'function', verbose_name='image')),
                ('descr', models.TextField(blank=True, help_text='APP \u529f\u80fd\u63cf\u8ff0', null=True, verbose_name='description')),
                ('position', models.IntegerField(blank=True, default=0, help_text='APP \u529f\u80fd\u4f4d\u7f6e', null=True, verbose_name='position')),
                ('display', models.BooleanField(default=True, help_text='APP \u529f\u80fd\u662f\u5426\u663e\u793a True for display && False for not display', verbose_name='display')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='\u6dfb\u52a0\u65f6\u95f4', verbose_name='createtime')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='\u4fee\u6539\u65f6\u95f4', verbose_name='modifytime')),
                ('app', models.ForeignKey(blank=True, help_text='APP', null=True, on_delete=django.db.models.deletion.CASCADE, to='dh.AppInfo', verbose_name='app')),
            ],
            options={
                'db_table': 'functioninfo',
                'verbose_name': 'functioninfo',
                'verbose_name_plural': 'functioninfo',
            },
        ),
    ]
