# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='createtime')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='modifytime')),
                ('title', models.CharField(blank=True, help_text='\u535a\u5ba2 \u6807\u9898', max_length=255, null=True, verbose_name='title')),
                ('blog', models.TextField(blank=True, help_text='\u535a\u5ba2 \u5185\u5bb9', null=True, verbose_name='blog')),
                ('tag', models.CharField(blank=True, help_text='\u535a\u5ba2 \u6807\u7b7e', max_length=255, null=True, verbose_name='tag')),
                ('visit', models.IntegerField(default=0, help_text='\u535a\u5ba2 \u8bbf\u95ee\u6570', verbose_name='visit')),
                ('evaluate', models.IntegerField(default=0, help_text='\u535a\u5ba2 \u8bc4\u4ef7\u6570', verbose_name='evaluate')),
                ('like', models.IntegerField(default=0, help_text='\u535a\u5ba2 \u70b9\u8d5e\u6570', verbose_name='like')),
                ('unlike', models.IntegerField(default=0, help_text='\u535a\u5ba2 \u88ab\u8e29\u6570', verbose_name='unlike')),
                ('follow', models.IntegerField(default=0, help_text='\u535a\u5ba2 \u5173\u6ce8\u6570', verbose_name='follow')),
                ('display', models.BooleanField(default=True, help_text='\u535a\u5ba2 \u662f\u5426\u663e\u793a True for display && False for not', verbose_name='display')),
                ('user', models.ForeignKey(blank=True, help_text='\u535a\u5ba2 \u4f5c\u8005', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo', verbose_name='author')),
            ],
            options={
                'verbose_name': 'bloginfo',
                'verbose_name_plural': 'bloginfo',
            },
        ),
        migrations.CreateModel(
            name='BlogSelectedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='createtime')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='modifytime')),
                ('title', models.CharField(blank=True, help_text='\u535a\u5ba2\u7cbe\u9009 \u6807\u9898', max_length=255, null=True, verbose_name='title')),
                ('url', models.URLField(blank=True, help_text='\u535a\u5ba2\u7cbe\u9009 \u7f51\u5740', max_length=255, null=True, verbose_name='url')),
                ('tag', models.CharField(blank=True, help_text='\u535a\u5ba2\u7cbe\u9009 \u6807\u7b7e', max_length=255, null=True, verbose_name='tag')),
                ('author', models.CharField(blank=True, help_text='\u535a\u5ba2\u7cbe\u9009 \u4f5c\u8005', max_length=255, null=True, verbose_name='author')),
                ('visit', models.IntegerField(default=0, help_text='\u535a\u5ba2\u7cbe\u9009 \u8bbf\u95ee\u6570', verbose_name='visit')),
                ('evaluate', models.IntegerField(default=0, help_text='\u535a\u5ba2\u7cbe\u9009 \u8bc4\u4ef7\u6570', verbose_name='evaluate')),
                ('like', models.IntegerField(default=0, help_text='\u535a\u5ba2\u7cbe\u9009 \u70b9\u8d5e\u6570', verbose_name='like')),
                ('unlike', models.IntegerField(default=0, help_text='\u535a\u5ba2\u7cbe\u9009 \u88ab\u8e29\u6570', verbose_name='unlike')),
                ('follow', models.IntegerField(default=0, help_text='\u535a\u5ba2\u7cbe\u9009 \u5173\u6ce8\u6570', verbose_name='follow')),
                ('display', models.BooleanField(default=True, help_text='\u535a\u5ba2\u7cbe\u9009 \u662f\u5426\u663e\u793a True for display && False for not', verbose_name='display')),
                ('user', models.ForeignKey(blank=True, help_text='\u535a\u5ba2\u7cbe\u9009 \u521b\u5efa\u8005', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo', verbose_name='author')),
            ],
            options={
                'verbose_name': 'blogselectedinfo',
                'verbose_name_plural': 'blogselectedinfo',
            },
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='createtime')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='modifytime')),
                ('tips', models.TextField(blank=True, help_text='\u77e5\u8bc6\u4fbf\u7b7e \u540d\u79f0', null=True, verbose_name='tips')),
                ('tag', models.CharField(blank=True, help_text='\u77e5\u8bc6\u4fbf\u7b7e \u6807\u7b7e', max_length=255, null=True, verbose_name='tag')),
                ('url', models.URLField(blank=True, help_text='\u77e5\u8bc6\u4fbf\u7b7e \u7f51\u5740', max_length=255, null=True, verbose_name='url')),
                ('visit', models.IntegerField(default=0, help_text='\u77e5\u8bc6\u4fbf\u7b7e \u8bbf\u95ee\u6570', verbose_name='visit')),
                ('evaluate', models.IntegerField(default=0, help_text='\u77e5\u8bc6\u4fbf\u7b7e \u8bc4\u4ef7\u6570', verbose_name='evaluate')),
                ('like', models.IntegerField(default=0, help_text='\u77e5\u8bc6\u4fbf\u7b7e \u70b9\u8d5e\u6570', verbose_name='like')),
                ('unlike', models.IntegerField(default=0, help_text='\u77e5\u8bc6\u4fbf\u7b7e \u88ab\u8e29\u6570', verbose_name='unlike')),
                ('follow', models.IntegerField(default=0, help_text='\u77e5\u8bc6\u4fbf\u7b7e \u5173\u6ce8\u6570', verbose_name='follow')),
                ('display', models.BooleanField(default=True, help_text='\u77e5\u8bc6\u4fbf\u7b7e \u662f\u5426\u663e\u793a True for display && False for not', verbose_name='display')),
                ('author', models.ForeignKey(blank=True, help_text='API \u521b\u5efa\u8005', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo', verbose_name='author')),
            ],
            options={
                'db_table': 'tips',
                'verbose_name': 'tips',
                'verbose_name_plural': 'tips',
            },
        ),
        migrations.CreateModel(
            name='UserTips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='createtime')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='modifytime')),
                ('status', models.BooleanField(default=True, help_text='\u77e5\u8bc6\u4fbf\u7b7e \u662f\u5426\u4e3a\u81ea\u5df1\u521b\u5efa True for create && False for follow', verbose_name='status')),
                ('tips', models.ForeignKey(blank=True, help_text='\u77e5\u8bc6\u4fbf\u7b7e', null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.Tips', verbose_name='tips')),
                ('user', models.ForeignKey(blank=True, help_text='\u7528\u6237', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo', verbose_name='user')),
            ],
            options={
                'db_table': 'usertips',
                'verbose_name': 'usertips',
                'verbose_name_plural': 'usertips',
            },
        ),
    ]
