# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='createtime')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='modifytime')),
                ('username', models.CharField(blank=True, help_text='\u7528\u6237\u540d', max_length=255, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, help_text='\u5bc6\u7801', max_length=255, null=True, verbose_name='password')),
                ('email', models.EmailField(blank=True, help_text='\u90ae\u7bb1', max_length=255, null=True, verbose_name='email')),
                ('login_page', models.URLField(blank=True, help_text='\u767b\u5f55\u9996\u9875', max_length=255, null=True, verbose_name='login_page')),
                ('display_bg', models.BooleanField(default=True, help_text='\u662f\u5426\u663e\u793a\u80cc\u666f\u56fe', verbose_name='display_bg')),
                ('classify', models.CharField(blank=True, choices=[(b'rx', 'RenXiang'), (b'fj', 'FengJing'), (b'kt', 'KaTong'), (b'bc', 'BianCheng'), (b'dw', 'DongWu'), (b'mx', 'MingXing'), (b'yx', 'YouXi'), (b'zs', 'ZheSi')], help_text='\u80cc\u666f\u56fe\u5206\u7c7b', max_length=255, null=True, verbose_name='classify')),
                ('search_engine', models.CharField(blank=True, choices=[(b'google', 'Google'), (b'bing', 'Bing'), (b'baidu', 'Baidu'), (b'sof', 'StackOverflow'), (b'tt', 'tt4it')], default=b'google', help_text='\u9ed8\u8ba4\u641c\u7d22\u5f15\u64ce', max_length=255, null=True, verbose_name='search_engine')),
                ('company', models.CharField(blank=True, help_text='\u6240\u5728\u516c\u53f8', max_length=255, null=True, verbose_name='company')),
                ('github', models.CharField(blank=True, help_text=b'Github', max_length=255, null=True, verbose_name='github')),
                ('sof', models.CharField(blank=True, help_text=b'StackOverflow', max_length=255, null=True, verbose_name='stackoverflow')),
                ('weibo', models.CharField(blank=True, help_text=b'Weibo', max_length=255, null=True, verbose_name='weibo')),
                ('rren', models.CharField(blank=True, help_text=b'Renren', max_length=255, null=True, verbose_name='renren')),
                ('v2ex', models.CharField(blank=True, help_text=b'v2ex', max_length=255, null=True, verbose_name='v2ex')),
                ('blog', models.CharField(blank=True, help_text=b'Blog', max_length=255, null=True, verbose_name='blog')),
                ('btc', models.CharField(blank=True, help_text=b'btc address', max_length=255, null=True, verbose_name='btc')),
                ('freeze', models.BooleanField(default=False, help_text='\u662f\u5426\u88ab\u51bb\u7ed3 True for freeze && False for not freeze', verbose_name='freeze')),
            ],
            options={
                'db_table': 'userinfo',
                'verbose_name': 'userinfo',
                'verbose_name_plural': 'userinfo',
            },
        ),
    ]
