# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import resume.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='createtime')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='modifytime')),
                ('resume', models.TextField(blank=True, help_text='resume content which markdown support', null=True, verbose_name='resume')),
                ('resume_html', models.TextField(blank=True, help_text='resume content which html support', null=True, verbose_name='resume_html')),
                ('pdf', models.FileField(blank=True, help_text='pdf or doc(x)', null=True, upload_to=resume.models.upload_path, verbose_name='pdf')),
                ('tag', models.CharField(blank=True, help_text='resume tag', max_length=255, null=True, verbose_name='tag')),
                ('visit', models.IntegerField(default=0, help_text='\u8bbf\u95ee\u6570', verbose_name='visit')),
                ('evaluate', models.IntegerField(default=0, help_text='\u8bc4\u4ef7\u6570', verbose_name='evaluate')),
                ('like', models.IntegerField(default=0, help_text='\u70b9\u8d5e\u6570', verbose_name='like')),
                ('unlike', models.IntegerField(default=0, help_text='\u88ab\u8e29\u6570', verbose_name='unlike')),
                ('follow', models.IntegerField(default=0, help_text='\u5173\u6ce8\u6570', verbose_name='follow')),
                ('display', models.BooleanField(default=True, help_text='\u662f\u5426\u663e\u793a True for display && False for not', verbose_name='display')),
                ('user', models.ForeignKey(blank=True, help_text='resume owner', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo', verbose_name='user')),
            ],
            options={
                'verbose_name': 'resumeinfo',
                'verbose_name_plural': 'resumeinfo',
            },
        ),
    ]
